from typing import Any

class PyEngineClient:
    @classmethod
    async def connect(cls, endpoint: str) -> PyEngineClient: ...
    async def add_vless_reality_outbound(self, **kwargs: Any) -> Any: ...
    async def remove_outbound(self, tag: str) -> Any: ...
    async def get_outbound_stats(self, tag: str) -> Any: ...
    async def close(self) -> Any: ...

def check_server_health(
    address: str,
    port: int,
    timeout_ms: int,
) -> tuple[bool, float | None, str | None]: ...
def check_servers_health(
    targets: list[tuple[str, str, int]],
    timeout_ms: int,
) -> list[tuple[str, bool, float | None, str | None]]: ...
def apply_killswitch_rules(*args: Any, **kwargs: Any) -> Any: ...
def remove_killswitch_rules(*args: Any, **kwargs: Any) -> Any: ...
def probe_kernel_killswitch_capability(*args: Any, **kwargs: Any) -> Any: ...
def build_dns_guard_config_json(*args: Any, **kwargs: Any) -> str: ...
def build_dns_routing_rule_json(*args: Any, **kwargs: Any) -> str: ...
