use crate::errors::{EngineError, EngineResult};
use tonic::transport::Channel;

// این ماژول توسط build.rs به‌صورت خودکار تولید می‌شود و دقیقاً منعکس‌کننده‌ی
// ساختار پکیج‌های proto است.
//
// This module is auto-generated by build.rs and exactly mirrors the proto
// package structure.
use crate::pb::xray;

use xray::app::proxyman::command::handler_service_client::HandlerServiceClient;
use xray::app::proxyman::command::{AddOutboundRequest, RemoveOutboundRequest};
use xray::app::stats::command::stats_service_client::StatsServiceClient;
use xray::app::stats::command::GetStatsRequest;
use xray::core::OutboundHandlerConfig;

/// آمار ترافیک یک outbound (بایت آپلود/دانلود از آخرین ریست).
/// Traffic stats for a single outbound (uplink/downlink bytes since last reset).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct OutboundStats {
    pub tag: String,
    pub uplink_bytes: i64,
    pub downlink_bytes: i64,
}

/// کلاینت اصلی که به gRPC API محلی xray-core وصل می‌شود. این پروسه‌ی
/// xray-core خودمان است (localhost)، نه یک سرور دوردست؛ API فقط برای
/// مدیریت local instance طراحی شده است.
///
/// The main client connecting to xray-core's local gRPC API. This is our
/// own xray-core process (localhost), not a remote server; the API is only
/// meant for managing a local instance.
// Clone اینجا ارزان است: کلاینت‌های تولیدشده توسط tonic فقط یک handle به
// کانال HTTP/2 مشترک را کپی می‌کنند، اتصال جدیدی باز نمی‌کنند.
//
// Clone is cheap here: tonic-generated clients just copy a handle to the
// shared HTTP/2 channel, they do not open a new connection.
#[derive(Clone)]
pub struct EngineClient {
    handler: HandlerServiceClient<Channel>,
    stats: StatsServiceClient<Channel>,
}

impl EngineClient {
    /// یک اتصال جدید به آدرس gRPC محلی xray-core برقرار می‌کند.
    /// آدرس پیش‌فرض معمولاً چیزی شبیه `http://127.0.0.1:10085` است که در
    /// کانفیگ xray-core زیر بخش `api`/`policy` تعریف می‌شود.
    ///
    /// Establishes a new connection to xray-core's local gRPC address.
    /// The default is typically something like `http://127.0.0.1:10085`,
    /// configured under the `api`/`policy` section of the xray-core config.
    pub async fn connect(endpoint: impl Into<String>) -> EngineResult<Self> {
        let endpoint = endpoint.into();
        let channel = Channel::from_shared(endpoint.clone())
            .map_err(|e| EngineError::InvalidOutboundConfig {
                reason: format!("invalid gRPC endpoint '{endpoint}': {e}"),
            })?
            .connect()
            .await
            .map_err(|source| EngineError::GrpcConnect {
                endpoint: endpoint.clone(),
                source,
            })?;

        Ok(Self {
            handler: HandlerServiceClient::new(channel.clone()),
            stats: StatsServiceClient::new(channel),
        })
    }

    /// یک outbound جدید (یک پروفایل سرور) را بدون ری‌استارت پروسه اضافه
    /// می‌کند. ساختن خودِ `OutboundHandlerConfig` (شامل تنظیمات پروتکل و
    /// transport/Reality) در این لایه انجام نمی‌شود — این وظیفه‌ی فاز ۲
    /// (Profile & Subscription Manager) است که آن را از یک لینک VLESS
    /// می‌سازد. این تابع فقط مسئول ارسال یک پیام از قبل ساخته‌شده است.
    ///
    /// Adds a new outbound (a server profile) without restarting the
    /// process. Building the `OutboundHandlerConfig` itself (protocol and
    /// transport/Reality settings) does not happen at this layer — that is
    /// phase 2's job (Profile & Subscription Manager), which builds it
    /// from a VLESS link. This function is only responsible for sending
    /// an already-built message.
    pub async fn add_outbound(&mut self, outbound: OutboundHandlerConfig) -> EngineResult<()> {
        let request = AddOutboundRequest {
            outbound: Some(outbound),
        };
        self.handler
            .add_outbound(request)
            .await
            .map_err(|status| EngineError::GrpcCall {
                method: "AddOutbound",
                status: Box::new(status),
            })?;
        Ok(())
    }

    /// یک outbound موجود را با تگش حذف می‌کند.
    /// Removes an existing outbound by its tag.
    pub async fn remove_outbound(&mut self, tag: &str) -> EngineResult<()> {
        let request = RemoveOutboundRequest {
            tag: tag.to_string(),
        };
        self.handler
            .remove_outbound(request)
            .await
            .map_err(|status| EngineError::GrpcCall {
                method: "RemoveOutbound",
                status: Box::new(status),
            })?;
        Ok(())
    }

    // نکته‌ی مهم معماری: HandlerService رسمی xray-core اصلاً متد
    // "ListOutbounds" ندارد (فقط Add/Remove/AlterInbound و
    // Add/Remove/AlterOutbound). یعنی نمی‌شود از خودِ xray-core پرسید چه
    // outbound هایی الان فعال‌اند — این لیست باید توسط خودِ orchestrator
    // (لایه‌ی پایتون، در فاز ۲) نگه‌داری شود، هر بار که add/remove انجام
    // می‌شود.
    //
    // Important architectural note: xray-core's official HandlerService has
    // no "ListOutbounds" RPC at all (only Add/Remove/AlterInbound and
    // Add/Remove/AlterOutbound). There is no way to ask xray-core itself
    // which outbounds are currently active — that list must be tracked by
    // the orchestrator itself (the Python layer, in phase 2) every time an
    // add/remove happens.

    /// آمار ترافیک آپلود/دانلود یک outbound را می‌خواند. از دو فراخوانی
    /// GetStats استفاده می‌کند چون xray-core شمارنده‌های uplink/downlink
    /// را جدا نگه می‌دارد (طبق قرارداد نام‌گذاری
    /// `outbound>>>{tag}>>>traffic>>>uplink`).
    ///
    /// Reads uplink/downlink traffic stats for an outbound. Uses two
    /// GetStats calls because xray-core keeps uplink/downlink counters
    /// separate (per its naming convention
    /// `outbound>>>{tag}>>>traffic>>>uplink`).
    pub async fn get_outbound_stats(&mut self, tag: &str) -> EngineResult<OutboundStats> {
        let uplink_bytes = self
            .fetch_stat_value(&format!("outbound>>>{tag}>>>traffic>>>uplink"))
            .await?;
        let downlink_bytes = self
            .fetch_stat_value(&format!("outbound>>>{tag}>>>traffic>>>downlink"))
            .await?;

        Ok(OutboundStats {
            tag: tag.to_string(),
            uplink_bytes,
            downlink_bytes,
        })
    }

    async fn fetch_stat_value(&mut self, stat_name: &str) -> EngineResult<i64> {
        let request = GetStatsRequest {
            name: stat_name.to_string(),
            reset: false,
        };
        let response =
            self.stats
                .get_stats(request)
                .await
                .map_err(|status| EngineError::GrpcCall {
                    method: "GetStats",
                    status: Box::new(status),
                })?;

        // اگر شمارنده هنوز وجود نداشته باشد (مثلاً هیچ ترافیکی رد نشده)،
        // xray-core ممکن است پاسخ خالی بدهد؛ صفر یک مقدار پیش‌فرض امن است.
        // If the counter doesn't exist yet (e.g. no traffic has passed),
        // xray-core may return an empty response; zero is a safe default.
        Ok(response.into_inner().stat.map(|s| s.value).unwrap_or(0))
    }
}
