//! engine-core: لایه‌ی Rust که مستقیماً با gRPC API باینری xray-core صحبت
//! می‌کند و به‌صورت یک ماژول پایتونی (`engine_core`) قابل import است.
//!
//! engine-core: the Rust layer that talks directly to xray-core's gRPC API,
//! exposed as an importable Python module (`engine_core`).

mod errors;
mod grpc_client;
mod vless_builder;

// درخت ماژول تولیدشده توسط build.rs (نگاه کنید به engine-core/build.rs)
// که دقیقاً منعکس‌کننده‌ی ساختار پکیج‌های proto رسمی xray-core است.
//
// The module tree generated by build.rs (see engine-core/build.rs), which
// exactly mirrors the official xray-core proto package structure.
mod pb {
    include!(concat!(env!("OUT_DIR"), "/pb_tree.rs"));
}

// فازهای بعدی این ماژول‌ها را اضافه می‌کنند؛ عمداً هنوز خالی/غایب هستند تا
// اسکلت فاز ۱ روی چیزی که هنوز طراحی نشده وابسته نباشد.
//
// Later phases will add these modules; deliberately absent for now so the
// phase-1 skeleton does not depend on things not yet designed.
// mod healthcheck;   // فاز ۳ / phase 3
// mod killswitch;    // فاز ۴ / phase 4
// mod dns_guard;     // فاز ۴ / phase 4

use errors::EngineError;
use grpc_client::EngineClient;
use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;

// خطای Rust را به یک استثنای پایتونی معمولی تبدیل می‌کند تا در سمت پایتون
// بشود آن را با try/except عادی گرفت، طبق اصل «core هرگز پروسه را نمی‌کشد».
//
// Converts a Rust error into a plain Python exception so it can be caught
// on the Python side with a normal try/except, per the "core never kills
// the process" principle.
impl From<EngineError> for PyErr {
    fn from(err: EngineError) -> PyErr {
        PyRuntimeError::new_err(err.to_string())
    }
}

/// پوشش پایتونی روی EngineClient. هر متد async است تا thread پایتون در
/// زمان انتظار برای gRPC بلاک نشود.
///
/// Python-facing wrapper around EngineClient. Every method is async so the
/// Python thread is not blocked while waiting on gRPC.
#[pyclass]
struct PyEngineClient {
    inner: EngineClient,
}

#[pymethods]
impl PyEngineClient {
    /// به آدرس gRPC محلی xray-core وصل می‌شود، مثلاً "http://127.0.0.1:10085".
    /// Connects to xray-core's local gRPC address, e.g. "http://127.0.0.1:10085".
    #[staticmethod]
    fn connect(py: Python<'_>, endpoint: String) -> PyResult<Bound<'_, PyAny>> {
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let inner = EngineClient::connect(endpoint).await?;
            Ok(PyEngineClient { inner })
        })
    }

    /// یک outbound کامل VLESS+Reality+Vision را از مقادیر خام می‌سازد و
    /// اضافه می‌کند. مقادیر آماده‌شده در فاز ۲ (subscription.py) هستند.
    ///
    /// Builds a complete VLESS+Reality+Vision outbound from raw values and
    /// adds it. The values are prepared by phase 2 (subscription.py).
    #[allow(clippy::too_many_arguments)]
    fn add_vless_reality_outbound<'py>(
        &self,
        py: Python<'py>,
        tag: String,
        uuid: String,
        flow: String,
        address: String,
        port: u32,
        network: String,
        sni: String,
        fingerprint: String,
        public_key_b64: String,
        short_id_hex: String,
        spider_x: String,
    ) -> PyResult<Bound<'py, PyAny>> {
        let mut client = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let params = vless_builder::VlessRealityParams {
                tag,
                uuid,
                flow,
                address,
                port,
                network,
                sni,
                fingerprint,
                public_key_b64,
                short_id_hex,
                spider_x,
            };
            let outbound = vless_builder::build_vless_reality_outbound(params)?;
            client.add_outbound(outbound).await?;
            Ok(())
        })
    }

    /// یک outbound را با تگش حذف می‌کند.
    /// Removes an outbound by its tag.
    fn remove_outbound<'py>(&self, py: Python<'py>, tag: String) -> PyResult<Bound<'py, PyAny>> {
        let mut client = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            client.remove_outbound(&tag).await?;
            Ok(())
        })
    }

    /// آمار آپلود/دانلود یک outbound را برمی‌گرداند: (tag, uplink_bytes, downlink_bytes).
    /// Returns upload/download stats for an outbound: (tag, uplink_bytes, downlink_bytes).
    fn get_outbound_stats<'py>(
        &self,
        py: Python<'py>,
        tag: String,
    ) -> PyResult<Bound<'py, PyAny>> {
        let mut client = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let stats = client.get_outbound_stats(&tag).await?;
            Ok((stats.tag, stats.uplink_bytes, stats.downlink_bytes))
        })
    }
}

/// تعریف ماژول پایتونی. نام باید دقیقاً با `name = "_engine_core"` در
/// Cargo.toml (بخش [lib]) یکسان باشد.
///
/// Defines the Python module. The name must exactly match
/// `name = "_engine_core"` in Cargo.toml's [lib] section.
#[pymodule]
fn _engine_core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyEngineClient>()?;
    Ok(())
}
